import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const rules = JSON.parse(readFileSync("fixtures/detection-rules.json", "utf8"));
const rulesJson = `${JSON.stringify(rules, null, 2)}\n`;

writeFileSync("python/agenthint/detection-rules.json", rulesJson);

writeFileSync(
  "src/generated-rules.ts",
  `// Generated by scripts/generate-rules.mjs from fixtures/detection-rules.json.
// Do not edit by hand.

export const KNOWN_AGENTS = ${JSON.stringify(rules.knownAgents, null, 2)} as const;

export type GeneratedKnownAgent = (typeof KNOWN_AGENTS)[number];

export const ENVIRONMENT_RULES = ${JSON.stringify(rules.environmentRules, null, 2)} as const;

export const PREFIX_RULES = ${JSON.stringify(rules.prefixRules, null, 2)} as const;

export const PARENT_PROCESS_RULES = ${JSON.stringify(rules.parentProcessRules, null, 2)} as const;
`,
);

const rustString = (value) => {
  let escaped = "";

  for (const character of value) {
    switch (character) {
      case '"':
        escaped += '\\"';
        break;
      case "\\":
        escaped += "\\\\";
        break;
      case "\n":
        escaped += "\\n";
        break;
      case "\r":
        escaped += "\\r";
        break;
      case "\t":
        escaped += "\\t";
        break;
      default: {
        const codePoint = character.codePointAt(0);
        escaped +=
          codePoint != null && codePoint < 0x20 ? `\\u{${codePoint.toString(16)}}` : character;
      }
    }
  }

  return `"${escaped}"`;
};
const rustStringArray = (values) => `&[${values.map((value) => rustString(value)).join(", ")}]`;
const rustEnvRules = rules.environmentRules
  .map((rule) => {
    return `    EnvironmentRule { agent: ${rustString(rule.agent)}, confidence: ${rule.confidence}, names: ${rustStringArray(rule.names)} },`;
  })
  .join("\n");
const rustPrefixRules = rules.prefixRules
  .map((rule) => {
    return `    PrefixRule { agent: ${rustString(rule.agent)}, confidence: ${rule.confidence}, prefix: ${rustString(rule.prefix)} },`;
  })
  .join("\n");
const rustParentRules = rules.parentProcessRules
  .map((rule) => {
    return `    ParentProcessRule { agent: ${rustString(rule.agent)}, names: ${rustStringArray(rule.names)} },`;
  })
  .join("\n");

writeFileSync(
  "crates/agenthint/src/generated_rules.rs",
  `// Generated by scripts/generate-rules.mjs from fixtures/detection-rules.json.
// Do not edit by hand.

pub(crate) struct EnvironmentRule {
    pub(crate) agent: &'static str,
    pub(crate) confidence: f32,
    pub(crate) names: &'static [&'static str],
}

pub(crate) struct PrefixRule {
    pub(crate) agent: &'static str,
    pub(crate) confidence: f32,
    pub(crate) prefix: &'static str,
}

pub(crate) struct ParentProcessRule {
    pub(crate) agent: &'static str,
    pub(crate) names: &'static [&'static str],
}

pub(crate) const ENVIRONMENT_RULES: &[EnvironmentRule] = &[
${rustEnvRules}
];

pub(crate) const PREFIX_RULES: &[PrefixRule] = &[
${rustPrefixRules}
];

pub(crate) const PARENT_PROCESS_RULES: &[ParentProcessRule] = &[
${rustParentRules}
];
`,
);

execFileSync(
  "npx",
  ["biome", "format", "--write", "src/generated-rules.ts", "python/agenthint/detection-rules.json"],
  {
    stdio: "inherit",
  },
);
execFileSync("cargo", ["fmt", "--all"], { stdio: "inherit" });
