// Generated by scripts/generate.mjs from fixtures/messages.json.
// Do not edit by hand.

pub(crate) const HELP: &str = "agenthint\n\nDetect whether the current process is probably running under an AI agent.\n\nUsage:\n  agenthint             Exit 0 if an agent is likely detected, otherwise 1\n  agenthint init <name> Print the recommended AI_AGENT value\n  agenthint doctor      Print detection details and setup advice\n  agenthint doctor --json\n                        Print detection details and setup advice as JSON\n  agenthint --json      Print the structured detection result\n  agenthint --explain   Print a short human-readable explanation\n  agenthint --version   Show the version\n  agenthint --help      Show this help";
pub(crate) const INIT_USAGE: &str =
    "agenthint init\n\nUsage:\n  agenthint init <agent-name>\n\nExample:\n  agenthint init codex";
pub(crate) const INIT_OUTPUT: &str =
    "AI_AGENT={agent}\n\nUse this value in the environment used for agent tool calls.";
pub(crate) const EXPLAIN_DETECTED: &str = "agent runtime likely detected";
pub(crate) const EXPLAIN_NOT_DETECTED: &str = "agent runtime not detected";
pub(crate) const DOCTOR_DETECTED: &str = "agent runtime likely detected";
pub(crate) const DOCTOR_NOT_DETECTED: &str = "agent runtime not detected";
pub(crate) const DOCTOR_SECURITY_TEXT: &str =
    "security: use this as a UX hint only, not as a trust boundary.";
pub(crate) const DOCTOR_SECURITY_JSON: &str = "use this as a UX hint only, not as a trust boundary";
pub(crate) const DOCTOR_EXPLICIT_TEXT: &str =
    "setup: AI_AGENT is set; this is the preferred explicit convention.";
pub(crate) const DOCTOR_HEURISTIC_TEXT: &str =
    "setup: detection is heuristic. Prefer setting AI_AGENT for a stable explicit signal.";
pub(crate) const DOCTOR_MISSING_TEXT: &str = "setup: no agent signal was detected.";
pub(crate) const DOCTOR_MISSING_HINT_TEXT: &str =
    "hint: agents should set AI_AGENT=<agent-name> before invoking tools.";
pub(crate) const DOCTOR_EXPLICIT_MESSAGE: &str =
    "AI_AGENT is set; this is the preferred explicit convention.";
pub(crate) const DOCTOR_HEURISTIC_MESSAGE: &str =
    "Detection is heuristic. Prefer setting AI_AGENT for a stable explicit signal.";
pub(crate) const DOCTOR_MISSING_MESSAGE: &str = "No agent signal was detected.";
pub(crate) const DOCTOR_MISSING_HINT: &str =
    "Agents should set AI_AGENT=<agent-name> before invoking tools.";
pub(crate) const DOCTOR_FALLBACK_HINT: &str =
    "Set AI_AGENT={agent} in the agent's tool-call environment.";

pub(crate) const AGENT_HINTS: &[(&str, &str)] = &[
    (
        "codex",
        "Set AI_AGENT=codex in AGENTS.md instructions or the shell environment used for tool calls.",
    ),
    (
        "claude-code",
        "Set AI_AGENT=claude-code in a PreToolUse hook or shell wrapper.",
    ),
    (
        "cursor",
        "Set AI_AGENT=cursor in Cursor agent hooks or workspace shell configuration.",
    ),
    (
        "gemini",
        "Set AI_AGENT=gemini in Gemini CLI hook or shell configuration.",
    ),
    (
        "copilot",
        "Set AI_AGENT=github-copilot-cli for Copilot CLI or AI_AGENT=github-copilot for Copilot agents.",
    ),
    (
        "windsurf",
        "Set AI_AGENT=windsurf in .windsurfrules or the workspace shell environment.",
    ),
    (
        "cline",
        "Set AI_AGENT=cline in .clinerules or the Cline shell environment.",
    ),
    (
        "roo-code",
        "Set AI_AGENT=roo-code in Roo Code rules or shell environment.",
    ),
    (
        "kilocode",
        "Set AI_AGENT=kilocode in .kilocode rules or shell environment.",
    ),
    (
        "opencode",
        "Set AI_AGENT=opencode in an OpenCode plugin or shell environment.",
    ),
    (
        "openclaw",
        "Set AI_AGENT=openclaw in an OpenClaw plugin or shell environment.",
    ),
    (
        "antigravity",
        "Set AI_AGENT=antigravity in .agents rules or shell environment.",
    ),
];
