// Generated by scripts/generate-rules.mjs from fixtures/detection-rules.json.
// Do not edit by hand.

pub(crate) struct EnvironmentRule {
    pub(crate) agent: &'static str,
    pub(crate) confidence: f32,
    pub(crate) names: &'static [&'static str],
}

pub(crate) struct PrefixRule {
    pub(crate) agent: &'static str,
    pub(crate) confidence: f32,
    pub(crate) prefix: &'static str,
}

pub(crate) struct ParentProcessRule {
    pub(crate) agent: &'static str,
    pub(crate) names: &'static [&'static str],
}

pub(crate) const ENVIRONMENT_RULES: &[EnvironmentRule] = &[
    EnvironmentRule {
        agent: "cursor",
        confidence: 0.92,
        names: &["CURSOR_AGENT"],
    },
    EnvironmentRule {
        agent: "gemini",
        confidence: 0.92,
        names: &["GEMINI_CLI"],
    },
    EnvironmentRule {
        agent: "codex",
        confidence: 0.92,
        names: &[
            "CODEX_SANDBOX",
            "CODEX_CI",
            "CODEX_THREAD_ID",
            "CODEX_HOME",
            "CODEX_USER_AGENT",
        ],
    },
    EnvironmentRule {
        agent: "augment-cli",
        confidence: 0.9,
        names: &["AUGMENT_AGENT"],
    },
    EnvironmentRule {
        agent: "amp",
        confidence: 0.9,
        names: &["AMP_CURRENT_THREAD_ID"],
    },
    EnvironmentRule {
        agent: "opencode",
        confidence: 0.9,
        names: &["OPENCODE_CLIENT", "OPENCODE"],
    },
    EnvironmentRule {
        agent: "claude-code",
        confidence: 0.9,
        names: &["CLAUDECODE", "CLAUDE_CODE", "CLAUDECODE_CWD"],
    },
    EnvironmentRule {
        agent: "copilot",
        confidence: 0.88,
        names: &[
            "COPILOT_MODEL",
            "COPILOT_ALLOW_ALL",
            "COPILOT_GITHUB_TOKEN",
            "COPILOT_CLI",
        ],
    },
    EnvironmentRule {
        agent: "replit",
        confidence: 0.65,
        names: &["REPL_ID"],
    },
    EnvironmentRule {
        agent: "antigravity",
        confidence: 0.9,
        names: &["ANTIGRAVITY_AGENT"],
    },
    EnvironmentRule {
        agent: "pi",
        confidence: 0.9,
        names: &["PI_CODING_AGENT"],
    },
    EnvironmentRule {
        agent: "kiro-cli",
        confidence: 0.9,
        names: &["KIRO_AGENT_PATH"],
    },
    EnvironmentRule {
        agent: "windsurf",
        confidence: 0.82,
        names: &["WINDSURF_AGENT"],
    },
    EnvironmentRule {
        agent: "cline",
        confidence: 0.82,
        names: &["CLINE_AGENT"],
    },
    EnvironmentRule {
        agent: "roo-code",
        confidence: 0.82,
        names: &["ROO_CODE_AGENT", "ROO_CODE"],
    },
    EnvironmentRule {
        agent: "kilocode",
        confidence: 0.82,
        names: &["KILOCODE_AGENT"],
    },
    EnvironmentRule {
        agent: "openclaw",
        confidence: 0.82,
        names: &["OPENCLAW_AGENT"],
    },
];

pub(crate) const PREFIX_RULES: &[PrefixRule] = &[
    PrefixRule {
        agent: "aider",
        confidence: 0.86,
        prefix: "AIDER_",
    },
    PrefixRule {
        agent: "cursor",
        confidence: 0.82,
        prefix: "CURSOR_",
    },
];

pub(crate) const PARENT_PROCESS_RULES: &[ParentProcessRule] = &[
    ParentProcessRule {
        agent: "codex",
        names: &["codex"],
    },
    ParentProcessRule {
        agent: "claude-code",
        names: &["claude", "claude-code"],
    },
    ParentProcessRule {
        agent: "cursor",
        names: &["cursor-agent", "cursor"],
    },
    ParentProcessRule {
        agent: "gemini",
        names: &["gemini"],
    },
    ParentProcessRule {
        agent: "aider",
        names: &["aider"],
    },
    ParentProcessRule {
        agent: "opencode",
        names: &["opencode"],
    },
    ParentProcessRule {
        agent: "amp",
        names: &["amp"],
    },
];
