// Generated by scripts/generate.mjs from fixtures/messages.json.
// Do not edit by hand.

export const MESSAGES = {
  help: "agenthint\n\nDetect whether the current process is probably running under an AI agent.\n\nUsage:\n  agenthint             Exit 0 if an agent is likely detected, otherwise 1\n  agenthint init <name> Print the recommended AI_AGENT value\n  agenthint doctor      Print detection details and setup advice\n  agenthint doctor --json\n                        Print detection details and setup advice as JSON\n  agenthint --json      Print the structured detection result\n  agenthint --explain   Print a short human-readable explanation\n  agenthint --version   Show the version\n  agenthint --help      Show this help",
  init: {
    usage:
      "agenthint init\n\nUsage:\n  agenthint init <agent-name>\n\nExample:\n  agenthint init codex",
    output: "AI_AGENT={agent}\n\nUse this value in the environment used for agent tool calls.",
  },
  explain: {
    detected: "agent runtime likely detected",
    notDetected: "agent runtime not detected",
  },
  doctor: {
    status: {
      detected: "agent runtime likely detected",
      notDetected: "agent runtime not detected",
    },
    securityText: "security: use this as a UX hint only, not as a trust boundary.",
    securityJson: "use this as a UX hint only, not as a trust boundary",
    explicitText: "setup: AI_AGENT is set; this is the preferred explicit convention.",
    heuristicText:
      "setup: detection is heuristic. Prefer setting AI_AGENT for a stable explicit signal.",
    missingText: "setup: no agent signal was detected.",
    missingHintText: "hint: agents should set AI_AGENT=<agent-name> before invoking tools.",
    explicitMessage: "AI_AGENT is set; this is the preferred explicit convention.",
    heuristicMessage:
      "Detection is heuristic. Prefer setting AI_AGENT for a stable explicit signal.",
    missingMessage: "No agent signal was detected.",
    missingHint: "Agents should set AI_AGENT=<agent-name> before invoking tools.",
    fallbackHint: "Set AI_AGENT={agent} in the agent's tool-call environment.",
    agentHints: {
      codex:
        "Set AI_AGENT=codex in AGENTS.md instructions or the shell environment used for tool calls.",
      "claude-code": "Set AI_AGENT=claude-code in a PreToolUse hook or shell wrapper.",
      cursor: "Set AI_AGENT=cursor in Cursor agent hooks or workspace shell configuration.",
      gemini: "Set AI_AGENT=gemini in Gemini CLI hook or shell configuration.",
      copilot:
        "Set AI_AGENT=github-copilot-cli for Copilot CLI or AI_AGENT=github-copilot for Copilot agents.",
      windsurf: "Set AI_AGENT=windsurf in .windsurfrules or the workspace shell environment.",
      cline: "Set AI_AGENT=cline in .clinerules or the Cline shell environment.",
      "roo-code": "Set AI_AGENT=roo-code in Roo Code rules or shell environment.",
      kilocode: "Set AI_AGENT=kilocode in .kilocode rules or shell environment.",
      opencode: "Set AI_AGENT=opencode in an OpenCode plugin or shell environment.",
      openclaw: "Set AI_AGENT=openclaw in an OpenClaw plugin or shell environment.",
      antigravity: "Set AI_AGENT=antigravity in .agents rules or shell environment.",
    },
  },
} as const;
